version: '3.8'

services:
  app:
    image: veremeioleg/kafkareader:1.1
    container_name: kafkareader-app
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kafkareader
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - ./logs:/app/logs
    networks:
      - app_network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: kafkareader-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kafkareader
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    name: kafkareader_app_network
    driver: bridge

volumes:
  postgres_data: